acreditacion:
    resource: "@AcreditacionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

acreditacion_usuario:
    resource: "@AcreditacionBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario
