acreditacion_pregunta:
    resource: "@AcreditacionBundle/Resources/config/routing/pregunta.yml"
    prefix:   /pregunta

acreditacion_homepage:
    path:     /
    defaults: { _controller: AcreditacionBundle:Default:index }
