departamento:
    resource: "@AcreditacionBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamento

municipio:
    resource: "@AcreditacionBundle/Resources/config/routing/municipio.yml"
    prefix:   /municipio

acreditacion_pregunta:
    resource: "@AcreditacionBundle/Resources/config/routing/pregunta.yml"
    prefix:   /pregunta

acreditacion_seccion:
    resource: "@AcreditacionBundle/Resources/config/routing/seccion.yml"
    prefix:   /seccion

acreditacion_centro_educativo:
    resource: "@AcreditacionBundle/Resources/config/routing/centro-educativo.yml"
    prefix:   /lista-centros-educativos

formulario_por_centro:
    resource: "@AcreditacionBundle/Resources/config/routing/formulario-centro-educativo.yml"
    prefix:   /formularioPorCentro

acreditacion_homepage:
    path:     /
    defaults: { _controller: AcreditacionBundle:Default:inicio }

acreditacion_recovery:
    path:     /recovery
    defaults: { _controller: AcreditacionBundle:Default:recovery }
acreditacion_login:
    path:     /admin
    defaults: { _controller: AcreditacionBundle:Default:admin }