centro_educativo_lista:
    path:     /
    defaults: { _controller: AcreditacionBundle:CentroEducativo:lista }
    methods:  GET

centro_educativo_add:
    path:     /agregar-centro-educativo
    defaults: { _controller: AcreditacionBundle:CentroEducativo:add }

centro_educativo_guardar:
    path:     /agregar-centro-educativo-guardar
    defaults: { _controller: AcreditacionBundle:CentroEducativo:addguardar }
    methods:  [POST]
centro_educativo_buscar:
    path:     /buscar
    defaults: { _controller: AcreditacionBundle:CentroEducativo:listanbr }
    methods:  [GET]

centro_educativo_borrar:
    path:     /{id}/borrar
    defaults: { _controller: AcreditacionBundle:CentroEducativo:borrar }
    methods:  [GET, POST]
centro_educativo_editar:
    path:     /{id}/editar
    defaults: { _controller: AcreditacionBundle:CentroEducativo:editarr }
    methods:  [GET, POST]

centro_educativo_form_dig_corr:
    path:     /form-digitar-corregir
    defaults: { _controller: AcreditacionBundle:CentroEducativo:form_dig_corr }
    methods:  [GET]

centro_educativo_form_dig_corr_cargar:
    path:     /form-digitar-corregir-cargar
    defaults: { _controller: AcreditacionBundle:CentroEducativo:digitarCorregirCargar }
    methods:  [POST]
centro_educativo_form_lista_revisar:
    path:     /form-lista-revisar
    defaults: { _controller: AcreditacionBundle:CentroEducativo:form_lista_revisar }
    methods:  [GET]
centro_educativo_form_lista_evaluar:
    path:     /form-lista-evaluar
    defaults: { _controller: AcreditacionBundle:CentroEducativo:form_lista_evaluar }
    methods:  [GET]
centro_educativo_cuotas:
    path:     /{id}/cuotas
    defaults: { _controller: AcreditacionBundle:CentroEducativo:cuotas }
    methods:  [GET]
centro_educativo_cuota_form:
    path:     /{id}/form-cuota
    defaults: { _controller: AcreditacionBundle:CentroEducativo:form_cuota }
    methods:  [GET]
centro_educativo_cuota_guardar:
    path:     /guardar-cuota
    defaults: { _controller: AcreditacionBundle:CentroEducativo:guardarcuota }
    methods:  [POST]
centro_educativo_cuota_borrar:
    path:     /{id}/{idcuota}/borrar-cuota
    defaults: { _controller: AcreditacionBundle:CentroEducativo:borrar_cuota }
    methods:  [GET, POST]
centro_educativo_cuota_editar:
    path:     /{id}/{idcuota}/editar-cuota
    defaults: { _controller: AcreditacionBundle:CentroEducativo:editar_cuota }
    methods:  [GET, POST]