respuesta_revisar:
    path:     /respuestaRevisar
    defaults: { _controller: AcreditacionBundle:FormularioPorCentroEducativo:respuestaRevisar }
    methods:  [POST]

formulario_calificar:
    path:     /calificar
    defaults: { _controller: AcreditacionBundle:FormularioPorCentroEducativo:calificar }
    methods:  [POST]
