reporte_cuantitativo_cualitativo:
    path:     /cuantitativo-cuantitativo
    defaults: { _controller: AcreditacionBundle:Reportes:cuantitativo_cualitativo }
    methods:  [GET]

reporte_x_estado:
    path:     /por-estado
    defaults: { _controller: AcreditacionBundle:Reportes:estado }
    methods:  [GET]
reporte_x_zona:
    path:     /por-zona
    defaults: { _controller: AcreditacionBundle:Reportes:zona }
    methods:  [GET]
reporte_x_rango_fecha:
    path:     /por-rango-fecha
    defaults: { _controller: AcreditacionBundle:Reportes:rango_fecha }
    methods:  [GET]
reporte_form_estado_actual_cedu:
    path:     /formulario-actual-centro-educativo
    defaults: { _controller: AcreditacionBundle:Reportes:form_estado_actual_cedu }
    methods:  [GET]
reporte_generar_estado_actual_cedu:
    path:     /reporte-estado-actual-centro-educativo
    defaults: { _controller: AcreditacionBundle:Reportes:pdf_estado_actual_cedu }
    methods:  [POST]
reporte_informe_cuantitativo:
    path:     /informeCuantitativo
    defaults: { _controller: AcreditacionBundle:Reportes:informeCuantitativo }
    methods:  [POST]
reporte_informe_cualitativo:
    path:     /informeCualitativo
    defaults: { _controller: AcreditacionBundle:Reportes:informeCualitativo }
    methods:  [POST]
reporte_diploma:
    path:     /diploma
    defaults: { _controller: AcreditacionBundle:Reportes:diploma }
    methods:  [POST]
reporte_noAcreditado:
    path:     /noAcreditado
    defaults: { _controller: AcreditacionBundle:Reportes:noAcreditado }
    methods:  [POST]
reporte_estadisticoGeneral:
    path:     /estadisticoGeneral
    defaults: { _controller: AcreditacionBundle:Reportes:estadisticoGeneral }
    methods:  [POST]
reporte_promedioCriterioIndicador:
    path:     /promedioCriterioIndicador
    defaults: { _controller: AcreditacionBundle:Reportes:promedioCriterioIndicador }
    methods:  [POST]
reporte_porDepartamento:
    path:     /porDepartamento
    defaults: { _controller: AcreditacionBundle:Reportes:porDepartamento }
    methods:  [POST]
consulta_publica_form:
    path:     /consulta-publica
    defaults: { _controller: AcreditacionBundle:Reportes:ConsultaPublica}
    methods:  [GET]
consulta_publica_form_buscar:
    path: /consulta-publica-reporte
    defaults: { _controller: AcreditacionBundle:Reportes:ConsultaPublicaBuscar}
    methods:  [POST]
