reporte_cuantitativo_cualitativo:
    path:     /cuantitativo-cuantitativo
    defaults: { _controller: AcreditacionBundle:Reportes:cuantitativo_cualitativo }
    methods:  [GET]

reporte_x_estado:
    path:     /por-estado
    defaults: { _controller: AcreditacionBundle:Reportes:estado }
    methods:  [GET]
reporte_x_zona:
    path:     /por-zona
    defaults: { _controller: AcreditacionBundle:Reportes:zona }
    methods:  [GET]
reporte_x_rango_fecha:
    path:     /por-rango-fecha
    defaults: { _controller: AcreditacionBundle:Reportes:zona }
    methods:  [GET]
reporte_x_prueba:
    path:     /prueba
    defaults: { _controller: AcreditacionBundle:Reportes:prueba }
    methods:  [GET]