reporte_cuantitativo_cualitativo:
    path:     /cuantitativo-cuantitativo
    defaults: { _controller: AcreditacionBundle:Reportes:cuantitativo_cualitativo }
    methods:  [GET]

reporte_x_estado:
    path:     /por-estado
    defaults: { _controller: AcreditacionBundle:Reportes:estado }
    methods:  [GET]
reporte_x_zona:
    path:     /por-zona
    defaults: { _controller: AcreditacionBundle:Reportes:zona }
    methods:  [GET]
reporte_x_rango_fecha:
    path:     /por-rango-fecha
    defaults: { _controller: AcreditacionBundle:Reportes:zona }
    methods:  [GET]
reporte_form_estado_actual_cedu:
    path:     /formulario-actual-centro-educativo
    defaults: { _controller: AcreditacionBundle:Reportes:form_estado_actual_cedu }
    methods:  [GET]
reporte_generar_estado_actual_cedu:
    path:     /reporte-estado-actual-centro-educativo
    defaults: { _controller: AcreditacionBundle:Reportes:pdf_estado_actual_cedu }
    methods:  [POST]