seccion_index:
    path:     /
    defaults: { _controller: "AcreditacionBundle:Seccion:index" }
    methods:  GET|POST

seccion_show:
    path:     /{id}/show
    defaults: { _controller: "AcreditacionBundle:Seccion:show" }
    methods:  GET

seccion_guardar:
    path:     /guardar
    defaults: { _controller: "AcreditacionBundle:Seccion:guardar" }
    methods:  POST

seccion_terminar:
    path:     /terminar
    defaults: { _controller: "AcreditacionBundle:Seccion:terminar" }
    methods:  POST
