usuario_index:
    path:     /
    defaults: { _controller: "AcreditacionBundle:Usuario:index" }
    methods:  GET

usuario_show:
    path:     /{id}/show
    defaults: { _controller: "AcreditacionBundle:Usuario:show" }
    methods:  GET

usuario_new:
    path:     /new
    defaults: { _controller: "AcreditacionBundle:Usuario:new" }
    methods:  [GET, POST]

usuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcreditacionBundle:Usuario:edit" }
    methods:  [GET, POST]

usuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcreditacionBundle:Usuario:delete" }
    methods:  [DELETE, GET]

login_fallo:
    path:     /fallo
    defaults: { _controller: "AcreditacionBundle:Usuario:fallo" }
    methods:  [POST, GET]