<?php

namespace AcreditacionBundle\Repository;

/**
 * AcreditacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcreditacionRepository extends \Doctrine\ORM\EntityRepository
{
}
