<?php

namespace AcreditacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuotaAnualPorGradoEscolarPorCentroEducativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuotaAnualPorGradoEscolarPorCentroEducativoRepository extends EntityRepository
{
}
