<?php

namespace AcreditacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DetalleCatalogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleCatalogoRepository extends EntityRepository
{
}
