<?php

namespace AcreditacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DetallePonderacionPreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetallePonderacionPreguntaRepository extends EntityRepository
{
}
