<?php

namespace AcreditacionBundle\Repository;

/**
 * EstadoAcreditacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoAcreditacionRepository extends \Doctrine\ORM\EntityRepository
{
}
