<?php

namespace AcreditacionBundle\Repository;

/**
 * ModalidadCentroEducativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModalidadCentroEducativoRepository extends \Doctrine\ORM\EntityRepository
{
}
