<?php

namespace AcreditacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeccionRepository extends EntityRepository
{
}
