<?php

namespace AcreditacionBundle\Repository;

/**
 * SeccionPorFormularioPorCentroEducativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeccionPorFormularioPorCentroEducativoRepository extends \Doctrine\ORM\EntityRepository
{
}
