<?php

namespace AcreditacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoAccionUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAccionUsuarioRepository extends EntityRepository
{
}
