<?php

namespace AcreditacionBundle\Repository;

/**
 * ViewFormularioPorCentroEducativoSeccionPonderacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewFormularioPorCentroEducativoSeccionPonderacionRepository extends \Doctrine\ORM\EntityRepository
{
}
