<?php

namespace AcreditacionBundle\Repository;

/**
 * ViewFormularioPorCentroEducativoIndicadorPonderacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewFormularioPorCentroEducativoIndicadorPonderacionRepository extends \Doctrine\ORM\EntityRepository
{
}
