<?php

namespace AcreditacionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ZonaGeograficaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZonaGeograficaRepository extends EntityRepository
{
}
