<?php

namespace AcreditacionBundle\Repository;

/**
 * ZonaCentroEducativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZonaCentroEducativoRepository extends \Doctrine\ORM\EntityRepository
{
}
